name: CI

on:
  push:
    branches: [ feature/* ]

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with black, isort
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: |
          pip install -r requirements.txt
          ls -la

      - name: Black check
        run:
          black --check .

      - name: Isort check
        run:
          isort --check .

      - name: Notify in telegram after image was pushed
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ${{ github.actor }} created commit:

            <b>WorkFlows:</b> <a href="https://github.com/${{ github.repository }}/actions">ActionsList</a>

            Commit with tag: ${{ steps.tag_version.outputs.new_tag }}

            Repository: ${{ github.repository }}

            Branch: ${{ github.ref }}

            <b>Pushed image:</b> h0d0user/flask_web_test:${{ steps.tag_version.outputs.new_tag }}

            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}