name: CI

on:
  push:
    branches: [ feature/* ]

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with black, isort
    container: python:3.9
    outputs:
      get_current_tag: ${{ steps.set_github_repository_short.outputs.github_repository_short }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: |
          pip install -r requirements.txt
          ls -la

      - name: Black check
        run:
          black --check .

      - name: Isort check
        run:
          isort --check .

      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        id: github_repository_short
        with:
          script: |
            github_repository_short = "${{ github.repository }}".split('/'[1])
            print(github_repository_short)

      - name: Set GitHub Repository Short name
        id: set_github_repository_short
        run: echo "::set-output name=github_repository_short::${{ steps.github_repository_short.outputs.github_repository_short }}"

      - name: Step To run on failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>!!! FAILED !!!</b>

            ${{ steps.github_repository_short.github_repository_short }}
            ${{ steps.set_github_repository_short.github_repository_short }}

            <b>Failed job:</b> https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}


      - name: Notify in telegram after image was pushed
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ${{ github.actor }} created commit:

            <b>WorkFlows:</b> <a href="https://github.com/${{ github.repository }}/actions">ActionsList</a>

            Commit with tag: ${{ steps.tag_version.outputs.new_tag }}

            Repository: ${{ github.repository }}

            Branch: ${{ github.ref }}

            <b>Pushed image:</b> <code>docker pull h0d0user/flask_web_test:${{ steps.tag_version.outputs.new_tag }}</code>

            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}