name: Publish

on:
  pull_request:
    branches: [ develop ]

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Publish on DockerHub
    container: python:3.9

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: h0d0user/flask_web_test:latest