name: Publish

on:
  pull_request:
    branches: [ develop ]

jobs:

  docker:
    runs-on: ubuntu-latest
    name: Publish on DockerHub

    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.REPOS_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Search
        run: |
          pwd
          ls -la

      - name: Build and push
        id: push_image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: h0d0user/flask_web_test:${{ steps.tag_version.outputs.new_tag }}

  telegram:
    needs: docker
    runs-on: ubuntu-latest
    name: Notify in Telegram

    steps:
      - name: Send telegram message after image was pushed
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

            Pushed image: ${{ needs.docker.push_image.outputs.tags }}
