name: Publish

on:
  pull_request:
    branches: [ develop ]

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Publish on DockerHub

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Search
        run: |
          pwd
          ls -la

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: h0d0user/flask_web_test:latest