name: Release

on:
  push:
    branches: [ master ]

jobs:

  docker:
    runs-on: ubuntu-latest
    name: Publish on DockerHub

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: h0d0user/flask_web_test:latest

  build:
    runs-on: ubuntu-latest
    name: Release

    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.REPOS_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}


  telegram:
    runs-on: ubuntu-latest
    name: Notification
    needs: build

    steps:
      - name: Notify telegram message after Released
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ${{ github.actor }} created commit:

            <b>WorkFlows:</b> <a href="https://github.com/${{ github.repository }}/actions">ActionsList</a>

            Repository: ${{ github.repository }}

            Branch: ${{ github.ref }}

            <b>Pushed image:</b> <code>docker pull h0d0user/flask_web_test:latest</code>

            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
