name: Release

on:
  push:
    branches: [ master ]

jobs:

  docker:
    runs-on: ubuntu-latest
    name: Publish on DockerHub

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: h0d0user/flask_web_test:latest

  build:
    runs-on: ubuntu-latest
    name: Release

    steps:
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}